# Generated by Django 4.2.5 on 2023-09-14 16:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('detail_code', models.CharField(max_length=127)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('serial_number', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('middle_name', models.CharField(max_length=127, null=True)),
                ('last_name', models.CharField(max_length=127)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('sex', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Malfunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2023, 9, 14, 19, 0, 16, 207968))),
                ('description', models.CharField(max_length=511)),
            ],
            options={
                'db_table': 'malfunction',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime(2023, 9, 14, 19, 0, 16, 206968))),
                ('order_deadline', models.DateTimeField()),
                ('description', models.CharField(max_length=511)),
                ('employee', models.ManyToManyField(to='service.employee')),
                ('malfunction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malfunction_order', to='service.malfunction')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_number', models.CharField(max_length=511)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'status_order',
            },
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'work_station',
            },
        ),
        migrations.CreateModel(
            name='UserTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=127)),
                ('color', models.CharField(max_length=127)),
                ('serial_number', models.CharField(max_length=127)),
                ('weight', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_transport',
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('description', models.CharField(max_length=511)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advice', models.CharField(max_length=511)),
                ('payment_method', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.paymentmethod')),
            ],
            options={
                'db_table': 'order_document',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=127, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.detail')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_document_order', to='service.orderdocument'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status_order', to='service.statusorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_order', to='service.usertransport'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_station_order', to='service.workstation'),
        ),
    ]
