# Generated by Django 4.2.6 on 2023-10-29 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 14, 28, 41, 328921)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 14, 28, 41, 328003)),
        ),
        migrations.AlterField(
            model_name='usertransport',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
